version: '1.0.{build}'

platform:
    - x64

configuration:
    - Debug
    - Release

os: Visual Studio 2017

install:
    - git submodule update --init --recursive

before_build:
    - cmake -G "Visual Studio 15 2017" .

build:
  project: inplace_string.sln
